#!/bin/bash
echo "begin compilation"
echo "object files will be created inside obj folder"

if [ ! -d obj ]; then
	echo "obj folder not found, creating obj folder"
	mkdir obj
else
	echo "obj folder found, cleaning obj folder"
	rm -rf obj/*
fi

g++ -std=gnu++11 -c source/main.cpp -o obj/main.o
g++ -std=gnu++11 -c source/akarin.cpp -o obj/akarin.o
g++ -std=gnu++11 -c source/akarin_math.cpp -o obj/akarin_math.o
g++ -std=gnu++11 -c source/akarin_map.cpp -o obj/akarin_map.o
g++ -std=gnu++11 -c source/akarin_matrix.cpp -o obj/akarin_matrix.o

if [ ! -d build ]; then
	echo "build folder not found, creating build folder"
	mkdir build
else
	echo "build folder found, cleaning build folder"
	rm -rf build/*
fi

g++ obj/main.o obj/akarin.o obj/akarin_math.o obj/akarin_map.o obj/akarin_matrix.o -o build/akarin -lsfml-graphics -lsfml-window -lsfml-system
echo "removing obj folder"
rm -rf obj
